version: '3.8'

services:
  frontend-build:
    image: hello-front-dev
    container_name: front-with-nginx
  nginx: 
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - frontend-build
  debug-helper:
    image: busybox
