version: '3.8'

services:
  server:
    image: hello-back-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 4000:4000
    environment:
      REDIS_URL: //redis:6379
      MONGO_URL: mongodb://the_username:the_password@mongo:27017/the_database
    volumes:
      - ./:/usr/src/app
    container_name: hello-back-dev
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo_data:/data/db
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    command: [ 'redis-server', '--appendonly', 'yes' ]
    volumes:
      - ./redis_data:/data
  debug-helper:
    image: busybox
